sudo: required
language: nix
cache:
  timeout: 1000
  directories:
  - $HOME/nix.store
before_cache:
- mkdir -p $HOME/nix.store
- nix copy --to file://$HOME/nix.store -f default.nix buildInputs
before_install:
- sudo mkdir -p /etc/nix
- echo "binary-caches = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
- echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
branches:
  only:
  - master
  - small-words
notifications:
  email:
  - false
script:
- nix-shell --pure --run 'make -j $NIX_BUILD_CORES -C proofs'
- nix-shell --pure --run 'make -C compiler CIL build tests-ci'
