[workspace]
authors = ["Nicolas Niclausse <nicolas.niclausse@inria.fr>"]
channels = ["conda-forge","nniclausse"]
name = "jasmin"
platforms = ["linux-64","osx-arm64"]
version = "0.1.0"

[tasks]
init_opam="opam init"
install_coq={cmd="opam repo add coq-released https://coq.inria.fr/opam/released",depends-on="init_opam"}
install_jasmin= { cmd="opam install jasmin" , depends-on="install_coq"}
install_dev={ cmd="opam install ." , depends-on="install_coq"}

[activation.env]
OPAMROOT="$CONDA_PREFIX/.opam"
CPATH="$CONDA_PREFIX/include"
LIBRARY_PATH="$CONDA_PREFIX/lib"
LD_LIBRARY_PATH="$CONDA_PREFIX/lib"
LANG="C"

[dependencies]
pkg-config = ">=0.29.2,<0.30"
gmp = ">=6.3.0,<7"
ppl = ">=1.2,<2"
opam = ">=2.1.3,<3"
mpfr = ">=4.2.1,<5"
zstd = ">=1.5.7,<2"
c-compiler = ">=1.11.0,<2"
pyyaml = ">=6,<7"
